### ISSUE TITLE
Apply the accent color to gnome-shell

### ISSUE THREAD

**Issue by Py-GNU-Unix** [lassekongo83/adw-colors#3]
It would be great to apply the accent color to gnome-shell too. I've found this extension -->  https://extensions.gnome.org/extension/4010/personalize/ that does something similar for gnome 3.38 but doesn't work on my version (42).

Thanks

**Comment by lassekongo83** [comment]
GTK is separate from gnome-shell. It's not as easy. See https://www.reddit.com/r/gnome/comments/vj2fjq/libadwaita_adwgtk3_gtk_named_colors/idtzahs/ on how to.

**Comment by Raubion** [comment]
Is this they only way? Because I found another [post on Reddit](https://www.reddit.com/r/gnome/comments/ubja92/how_can_i_change_the_color_of_the_top_bar_in/) explaining how to change the top panel. It seems easier. It suggests to create a file in ~/.themes/YourTheme/gnome-shell/gnome-shell.css containing:

`#panel { background-color: green; }
#panel:overview { background-color: blue; }`

The shell theme can then be enabled via the Tweak tool. I've tried it and it works, but I can't seem to find the other parts. But wouldn't this be more like your method to create adw-colors? Any idea where to find the other parts? Or do you know them?

**Comment by Raubion** [comment]
Ah right, that's a shame. I figured if I could find the variables for the colors of the dropdown menu of the clock with the notifications and of the menu with the settings and logoff options as well as the cards, buttons and the accent color, I'd be good. Then we could easily make cool themes where shell and libadwaita matched. I did find the variable for the overview and activities, so thought I was close ;)
