### ISSUE TITLE
apply a custom light and a custom dark theme

### ISSUE THREAD

**Issue by Radical4ever** [lassekongo83/adw-colors#7]
Hi, i love these themes so much, but i have a question. is it possible to set a gtk.css theme for light theme and gtk.css dark theme for the system?. thank you

**Comment by lassekongo83** [comment]
As far as I know there is no way to use both.

If you use a light theme customization I know some apps like eog and totem can look a bit off. So editing the app's `.desktop` files should work. Instead of `Exec eog %u` use `Exec=env GTK_THEME=adw-gtk3 eog %u`. Then eog should use the light theme. This will have to be done on a per application basis.

**Comment by Radical4ever** [comment]
Oh well, guess i cannot use both solaeized light and dark theme.
